#!/usr/bin/env python3
"""Hygiene — the junk a product accumulates, and the few exposures a pattern can
prove, measured on every run. Stdlib only, like the rest of the harness.

More and more of what Verdict reviews was generated by a model and shipped by
someone who never read it. Three tiers, and the tier decides who acts:

  1  near-certain and harmful — a live key in the source, a committed secrets
     file, a client-side variable named as a secret, database rules open to
     everyone, a debugger left in: filed as findings by verdict-finalize,
     `source: "hygiene"`
  2  junk — swallowed errors, unused imports, oversized files, TODOs,
     commented-out code, debug logging, copied functions: tracked in a ledger,
     never a finding
  3  leads — a swallow around a secret write, a security read that fails open, a
     placeholder secret default, a forwarded header, a wildcard CORS rule: handed
     to the tester to read first, never filed here

Every item carries a fingerprint (kind, path, normalized line, occurrence), so a
line that moves keeps its identity and a line that goes away resolves. A secret
is redacted where it is found: its value never reaches facts, state or a report.
Lines are numbered by splitting on "\\n", never `splitlines()`, which also breaks
on U+2028 inside a string literal and shifts every later line number.
"""

from __future__ import annotations

import ast
import base64
import hashlib
import io
import json
import math
import os
import re
import subprocess
import tokenize
from pathlib import Path

try:
    from .census import _SKIP_DIRS
except ImportError:  # imported as a plain module beside census.py
    from census import _SKIP_DIRS

CODE_SUFFIXES = {".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}
SCANNED_SUFFIXES = CODE_SUFFIXES | {
    ".json", ".yml", ".yaml", ".toml", ".ini", ".cfg", ".env", ".properties", ".xml",
    ".sh", ".md", ".txt", ".tf", ".conf", ".sql", ".rules", ""}
FILE_CAP = 5000          # files scanned per run; reaching it is reported, never silent
MAX_BYTES = 1_000_000    # a minified bundle is not source anybody maintains
OVERSIZED_LINES = 2000
DUPLICATE_MIN_LINES = 8
LEAD_CAP = 60            # leads written to facts; the total is always exact
LEDGER_CAP = 5000        # ledger rows; past it the summary stays exact and deltas stop

SEVERITY = {
    "secret_in_code": "Critical",
    "secret_file_tracked": "Critical",
    "public_env_secret": "Critical",
    "open_database_rules": "Critical",
    "debugger_statement": "Minor",
}
TITLE = {
    "secret_in_code": "A live credential is committed in the source",
    "secret_file_tracked": "A secrets file is committed to the repository",
    "public_env_secret": "A secret is exposed through a client-side environment variable",
    "open_database_rules": "Database access rules let anyone read or write",
    "debugger_statement": "A debugger statement is left in shipped code",
}
TIER2_KINDS = ("broad_swallow", "unused_import", "oversized_file", "todo_comment",
               "commented_out_code", "console_debug", "duplicate_function")
_LEAD_ORDER = {k: n for n, k in enumerate((
    "swallow_around_sensitive_write", "security_read_fails_open",
    "placeholder_security_default", "forwarded_header_trust", "wildcard_cors",
    "raw_html_injection", "shell_or_eval", "tls_verify_off", "public_env_key_name",
    "rls_policy_using_true", "env_file_committed", "module_never_imported"))}

_TEST_DIRS = {"test", "tests", "__tests__", "spec", "specs", "fixtures", "__fixtures__",
              "testdata", "e2e"}
_SCRIPT_DIRS = {"scripts", "script", "bin", "tools", "tool"}

# ── tier 1 patterns ───────────────────────────────────────────────────────
_SECRET_PATTERNS = (
    ("anthropic key", re.compile(r"sk-ant-(?:api|admin|oat)\d{2}-[A-Za-z0-9_-]{20,}")),
    ("openai key", re.compile(r"\bsk-(?!ant-)(?:proj-|svcacct-)?[A-Za-z0-9_-]{32,}")),
    ("aws access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("github token", re.compile(
        r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36}\b|\bgithub_pat_[A-Za-z0-9_]{40,}")),
    ("slack token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}")),
    ("google api key", re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b")),
    ("telegram bot token", re.compile(r"\b\d{8,10}:AA[A-Za-z0-9_-]{33}\b")),
    ("stripe live key", re.compile(r"\b[rs]k_live_[A-Za-z0-9]{20,}")),
)
_PRIVATE_KEY = re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP |ENCRYPTED )?PRIVATE KEY-----")
_BASE64_LINE = re.compile(r"^[A-Za-z0-9+/=]{40,}$")
_JWT = re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.(eyJ[A-Za-z0-9_-]{10,})\.[A-Za-z0-9_-]{10,}")
_PLACEHOLDER = re.compile(
    r"x{4,}|example|your[_-]|fake|dummy|sample|placeholder|change_?me|redacted|test",
    re.IGNORECASE)
_SEQUENTIAL = ("0123", "1234", "2345", "3456", "4567", "5678", "6789", "abcd", "bcde", "wxyz")
_PUBLIC_ENV_SECRET = re.compile(
    r"\b(?:NEXT_PUBLIC|VITE|EXPO_PUBLIC|REACT_APP|NUXT_PUBLIC|PUBLIC)_[A-Z0-9_]*"
    r"(?:SECRET|PRIVATE|SERVICE_ROLE|PASSWORD)[A-Z0-9_]*\b")
_FIREBASE_OPEN = re.compile(
    r"allow\s+[\w\s,]*:\s*if\s+true\s*;|\"\.(?:read|write)\"\s*:\s*(?:true|\"true\")")
_RLS_DISABLED = re.compile(r"\bdisable\s+row\s+level\s+security\b", re.IGNORECASE)
_ENV_FILE = re.compile(r"(?:^|/)\.env(?:\.[\w.-]+)?$")
_ENV_TEMPLATE = re.compile(r"\.(?:example|sample|template|dist|defaults|test|ci)$", re.IGNORECASE)
_ENV_SECRET_BY_CONVENTION = re.compile(r"\.local$|\.production$|\.prod$", re.IGNORECASE)
_SECRETISH_ASSIGN = re.compile(
    r"^\s*(?:export\s+)?([A-Z0-9_]*(?:SECRET|PASSWORD|PRIVATE|TOKEN|KEY)[A-Z0-9_]*)\s*=\s*(\S+)")
_KEY_CONTAINER = re.compile(r"\.(?:p12|pfx|jks|keystore)$|^id_(?:rsa|dsa|ecdsa|ed25519)$",
                            re.IGNORECASE)
_JS_DEBUGGER = re.compile(r"^\s*debugger\s*;?\s*(?://.*)?$")
_PY_DEBUGGER = re.compile(r"\bbreakpoint\(\s*\)|\b(?:i?pdb)\.set_trace\(|^\s*import\s+i?pdb\b")

# ── tier 2 patterns ───────────────────────────────────────────────────────
_JS_EMPTY_CATCH = re.compile(
    r"catch\s*(?:\([^)]*\))?\s*\{\s*\}"
    r"|\.catch\(\s*(?:\([^)]*\)|[A-Za-z_$][\w$]*)?\s*=>\s*\{\s*\}\s*\)")
_TODO = re.compile(r"\b(?:TODO|FIXME|HACK|XXX)\b")
_JS_COMMENT_TODO = re.compile(r"(?://|/\*|^\s*\*).*?\b(?:TODO|FIXME|HACK|XXX)\b")
_CONSOLE = re.compile(r"\bconsole\.(?:log|debug|trace)\(")
_JS_CODEY_COMMENT = re.compile(
    r"^\s*//\s*(?:const |let |var |import |export |return |await |if \(|for \(|\}|"
    r"[\w.$]+\(.*\);?\s*$|[\w.$]+\s*=\s*.+;\s*$)")
_JS_IMPORT = re.compile(
    r"^[ \t]*import\s+(?:type\s+)?(?P<spec>\{[^}]*\}|[\w$]+(?:\s*,\s*\{[^}]*\})?|\*\s+as\s+[\w$]+)"
    r"\s+from\s+['\"][^'\"]+['\"]", re.MULTILINE)
_RICH = (ast.Call, ast.Assign, ast.AugAssign, ast.AnnAssign, ast.Import, ast.ImportFrom,
         ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Return, ast.If, ast.For,
         ast.While, ast.With, ast.Raise, ast.Delete, ast.Await)

# ── tier 3 patterns ───────────────────────────────────────────────────────
_WRITE_CALL = re.compile(
    r"\.\s*(?:set|save|write|delete|remove|rename|commit|put|update|insert|replace|dump|store|unlink)\w*\s*\("
    r"|\b(?:save|write|store|persist)\w*\s*\(", re.IGNORECASE)
_READ_CALL = re.compile(r"\.\s*(?:get|read|load|fetch|lookup)\w*\s*\(|\b(?:get|read|load)_\w*\s*\(",
                        re.IGNORECASE)
_SENSITIVE = re.compile(
    r"secret|token|passw|totp|otp|auth|session|credential|recovery|api[_-]?key|private"
    r"|crash|state|ledger|balance|payment", re.IGNORECASE)
_LINE_LEADS = (
    ("wildcard_cors", re.compile(
        r"Access-Control-Allow-Origin['\"]?\s*[:,=]\s*['\"]\*['\"]|allow_origins?\s*=\s*\[?\s*['\"]\*"
        r"|origin\s*:\s*['\"]\*['\"]"),
     "a wildcard CORS rule — check what the route returns and whether it needs a login"),
    ("raw_html_injection", re.compile(r"dangerouslySetInnerHTML|\bv-html\s*=|\.innerHTML\s*=(?!=)"),
     "raw HTML goes into the page — check that what reaches it is sanitized"),
    ("shell_or_eval", re.compile(
        r"shell\s*=\s*True|\bos\.system\(|(?<![\w.])eval\(|(?<![\w.])exec\("
        r"|child_process\.(?:exec|execSync)\(|\bexecSync\(\s*`"),
     "a shell or eval call — check whether any part of the string can come from outside"),
    ("tls_verify_off", re.compile(
        r"verify\s*=\s*False|\bssl\s*=\s*False|CERT_NONE|rejectUnauthorized\s*:\s*false"
        r"|NODE_TLS_REJECT_UNAUTHORIZED"),
     "TLS verification is turned off"),
    ("forwarded_header_trust", re.compile(r"X-Forwarded-(?:Proto|For|Host)|CF-Connecting-IP|X-Real-IP",
                                          re.IGNORECASE),
     "a forwarded header is read — check that it is honoured only behind a trusted proxy"),
    ("public_env_key_name", re.compile(
        r"\b(?:NEXT_PUBLIC|VITE|EXPO_PUBLIC|REACT_APP|NUXT_PUBLIC)_[A-Z0-9_]*(?:KEY|TOKEN)[A-Z0-9_]*"),
     "a client-side variable named like a credential — publishable and anon keys are fine, secret keys are not"),
)
_RLS_OPEN_POLICY = re.compile(r"using\s*\(\s*true\s*\)", re.IGNORECASE)
_PLACEHOLDER_SECURITY_DEFAULT = re.compile(
    r"^\s*([A-Z0-9_]*(?:SALT|SECRET|KEY|TOKEN|PASSWORD|PASS)[A-Z0-9_]*)\s*=\s*['\"]?"
    r"(?:change_?me\w*|changeme\w*|your[_-]\w*|x{3,}|secret|password|replace_?me\w*|todo)['\"]?\s*$",
    re.IGNORECASE)
_ENTRY_FILE = re.compile(
    r"(?:^|/)(?:Makefile|Dockerfile[\w.-]*|docker-compose[\w.-]*|Procfile|[\w.-]*\.service[\w.-]*"
    r"|pyproject\.toml|setup\.cfg|package\.json|README[\w.-]*)$|\.sh$|^\.github/workflows/",
    re.IGNORECASE)


def is_test_path(rel: str) -> bool:
    p = rel.replace("\\", "/").lower()
    if any(d in _TEST_DIRS for d in p.split("/")[:-1]):
        return True
    return re.search(r"(?:^|/)(?:test_[^/]*\.py|[^/]*_test\.py|conftest\.py"
                     r"|[^/]*\.(?:test|spec)\.[cm]?[jt]sx?)$", p) is not None


def _is_script_path(rel: str) -> bool:
    parts = rel.lower().split("/")
    return parts[0] in _SCRIPT_DIRS or ".config." in parts[-1]


def _tracked(repo: Path) -> tuple[list[str], bool]:
    proc = subprocess.run(["git", "-C", str(repo), "ls-files", "-z"], capture_output=True)
    if proc.returncode == 0:
        paths = [p for p in proc.stdout.decode("utf-8", "replace").split("\0") if p]
    else:
        paths = []
        for root, dirs, names in os.walk(repo):
            dirs[:] = sorted(d for d in dirs if d not in _SKIP_DIRS)
            paths += [Path(root, n).relative_to(repo).as_posix() for n in sorted(names)]
            if len(paths) > FILE_CAP:
                break
    keep = [p for p in paths if not set(p.split("/")[:-1]) & _SKIP_DIRS]
    return keep[:FILE_CAP], len(keep) > FILE_CAP


def _read(repo: Path, rel: str) -> str | None:
    p = repo / rel
    try:
        if p.stat().st_size > MAX_BYTES:
            return None
        data = p.read_bytes()
    except OSError:
        return None
    if b"\0" in data[:4096]:
        return None
    return data.decode("utf-8", errors="replace")


def _lines(text: str) -> list[str]:
    return [ln.rstrip("\r") for ln in text.split("\n")]


def _item(kind, tier, rel, line, text, why, *, redacted=None, key=None):
    shown = redacted if redacted is not None else text.strip()[:120]
    return {"kind": kind, "tier": tier, "path": rel, "line": line, "excerpt": shown, "why": why,
            "_key": key if key is not None else (redacted if redacted is not None
                                                 else " ".join(text.split()))}


def _fingerprint(items: list) -> list:
    seen: dict = {}
    for it in items:
        base = (it["kind"], it["path"], it.pop("_key"))
        n = seen.get(base, 0)
        seen[base] = n + 1
        it["fingerprint"] = hashlib.sha1("\0".join((*base, str(n))).encode("utf-8")).hexdigest()[:16]
    return items


def _entropy(s: str) -> float:
    if not s:
        return 0.0
    return -sum(s.count(c) / len(s) * math.log2(s.count(c) / len(s)) for c in set(s))


def _looks_live(token: str) -> bool:
    low = token.lower()
    if _PLACEHOLDER.search(low) or any(seq in low for seq in _SEQUENTIAL):
        return False
    tail = low[-24:]
    return len(tail) < 16 or _entropy(tail) >= 3.0


def _jwt_role(middle: str):
    try:
        return json.loads(base64.urlsafe_b64decode(middle + "=" * (-len(middle) % 4))).get("role")
    except (ValueError, AttributeError, UnicodeDecodeError):
        return None


def _redact(name: str, token: str) -> str:
    return f"{name}: <{len(token)} chars, ends …{token[-4:]}>"


# ── tier 1 ────────────────────────────────────────────────────────────────
def _secrets(rel, lines):
    out = []
    for i, line in enumerate(lines, 1):
        for name, rx in _SECRET_PATTERNS:
            for m in rx.finditer(line):
                if _looks_live(m.group(0)):
                    out.append(_item("secret_in_code", 1, rel, i, line,
                                     f"a {name} in the source: anyone who can read the repository can use it",
                                     redacted=_redact(name, m.group(0))))
        for m in _JWT.finditer(line):
            if _jwt_role(m.group(1)) == "service_role":
                out.append(_item("secret_in_code", 1, rel, i, line,
                                 "a Supabase service_role key: it bypasses row-level security",
                                 redacted=_redact("supabase service_role key", m.group(0))))
        if _PRIVATE_KEY.search(line):
            nxt = next((ln.strip() for ln in lines[i:i + 3] if ln.strip()), "")
            if _BASE64_LINE.match(nxt):
                out.append(_item("secret_in_code", 1, rel, i, line, "a private key in the source",
                                 redacted="private key block"))
    return out


def _secret_files(repo, files):
    items, leads = [], []
    for rel in files:
        if is_test_path(rel):
            continue
        name = rel.rsplit("/", 1)[-1]
        if _ENV_FILE.search(rel) and not _ENV_TEMPLATE.search(name):
            text = _read(repo, rel) or ""
            secret = next((m for m in map(_SECRETISH_ASSIGN.match, _lines(text))
                           if m and not m.group(1).startswith(("NEXT_PUBLIC_", "VITE_", "EXPO_PUBLIC_",
                                                               "REACT_APP_", "PUBLIC_"))
                           and _looks_live(m.group(2).strip("'\""))), None)
            if secret or _ENV_SECRET_BY_CONVENTION.search(name):
                items.append(_item("secret_file_tracked", 1, rel, 1, name,
                                   "an environment file is committed: whatever it holds stays in the history",
                                   redacted=f"{name} committed" + (f", sets {secret.group(1)}" if secret else "")))
            else:
                leads.append(_item("env_file_committed", 3, rel, 1, name,
                                   "an environment file is committed — check that nothing in it is secret"))
        elif _KEY_CONTAINER.search(name):
            items.append(_item("secret_file_tracked", 1, rel, 1, name, "a key file is committed",
                               redacted=f"{name} committed"))
        elif name.endswith(".pem") and "PRIVATE KEY" in (_read(repo, rel) or ""):
            items.append(_item("secret_file_tracked", 1, rel, 1, name, "a private key file is committed",
                               redacted=f"{name} committed"))
        elif name.endswith(".json"):
            text = _read(repo, rel) or ""
            if '"service_account"' in text and '"private_key"' in text:
                items.append(_item("secret_file_tracked", 1, rel, 1, name,
                                   "a cloud service-account key is committed", redacted=f"{name} committed"))
    return items, leads


def _public_env(rel, lines):
    return [_item("public_env_secret", 1, rel, i, line,
                  f"{m.group(0)} is bundled into the client: every visitor can read it",
                  redacted=m.group(0))
            for i, line in enumerate(lines, 1) for m in _PUBLIC_ENV_SECRET.finditer(line)]


def _open_rules(rel, name, suffix, lines):
    out = []
    firebase = name in ("firestore.rules", "storage.rules", "database.rules.json") or suffix == ".rules"
    for i, line in enumerate(lines, 1):
        if firebase and _FIREBASE_OPEN.search(line):
            out.append(_item("open_database_rules", 1, rel, i, line,
                             "a rule that lets every client read or write"))
        if suffix == ".sql" and _RLS_DISABLED.search(line):
            out.append(_item("open_database_rules", 1, rel, i, line,
                             "row-level security is switched off: the anon key can read every row"))
    return out


def _debuggers(rel, suffix, lines):
    rx = _PY_DEBUGGER if suffix == ".py" else _JS_DEBUGGER
    return [_item("debugger_statement", 1, rel, i, line, "execution stops here in production")
            for i, line in enumerate(lines, 1) if rx.search(line)]


# ── tier 3, line-level ────────────────────────────────────────────────────
def _line_leads(rel, lines):
    out = []
    for i, line in enumerate(lines, 1):
        for kind, rx, why in _LINE_LEADS:
            if rx.search(line) and not _PUBLIC_ENV_SECRET.search(line):
                context = " | ".join(ln.strip() for ln in lines[max(0, i - 3):i - 1] if ln.strip())
                out.append(_item(kind, 3, rel, i, line,
                                 why + (f" (just above: {context[:160]})" if context else "")))
    return out


def _env_placeholders(rel, name, lines):
    if not (name.startswith(".env") and _ENV_TEMPLATE.search(name)) and not name.endswith(".env.example"):
        return []
    return [_item("placeholder_security_default", 3, rel, i, line,
                  f"{m.group(1)} ships with a placeholder — check that startup refuses it")
            for i, line in enumerate(lines, 1) if (m := _PLACEHOLDER_SECURITY_DEFAULT.match(line))]


# ── Python ────────────────────────────────────────────────────────────────
def _broad(handler) -> bool:
    return handler.type is None or (isinstance(handler.type, ast.Name)
                                    and handler.type.id in ("Exception", "BaseException"))


def _does_nothing(body) -> bool:
    if len(body) != 1:
        return False
    s = body[0]
    return isinstance(s, (ast.Pass, ast.Continue)) or (
        isinstance(s, ast.Expr) and isinstance(s.value, ast.Constant) and s.value.value is Ellipsis)


def _empty_value(v) -> bool:
    if isinstance(v, ast.Constant):
        return v.value in (None, False, "", 0)
    if isinstance(v, (ast.List, ast.Tuple, ast.Set)):
        return not v.elts
    if isinstance(v, ast.Dict):
        return not v.keys
    return False


def _empties(body) -> bool:
    return bool(body) and all(isinstance(s, ast.Assign) and _empty_value(s.value) for s in body)


def _catches_import_error(handler) -> bool:
    names = {"ImportError", "ModuleNotFoundError"}
    t = handler.type
    if isinstance(t, ast.Name):
        return t.id in names
    if isinstance(t, ast.Tuple):
        return any(isinstance(e, ast.Name) and e.id in names for e in t.elts)
    return False


def _python(rel, text, lines, test, items, leads, imported):
    try:
        tree = ast.parse(text)
    except (SyntaxError, ValueError):
        return None
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(a.name.split(".")[0] for a in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.level == 0:
                imported.add(node.module.split(".")[0])
            imported.update(a.name.split(".")[0] for a in node.names)
        elif isinstance(node, ast.Try):
            span = "\n".join(lines[node.lineno - 1:(node.body[-1].end_lineno or node.lineno)])
            for h in node.handlers:
                if not _broad(h):
                    continue
                if _does_nothing(h.body):
                    if not test:
                        items.append(_item("broad_swallow", 2, rel, h.lineno, lines[h.lineno - 1],
                                           "a broad exception handler that does nothing"))
                    if not test and _WRITE_CALL.search(span) and _SENSITIVE.search(span):
                        leads.append(_item(
                            "swallow_around_sensitive_write", 3, rel, h.lineno, lines[h.lineno - 1],
                            "a write to security or persisted state can fail here with nobody told — "
                            "check what the caller then assumes happened"))
                elif not test and _empties(h.body) and _READ_CALL.search(span) and _SENSITIVE.search(span):
                    leads.append(_item(
                        "security_read_fails_open", 3, rel, h.lineno, lines[h.lineno - 1],
                        "a failed read of security state becomes an empty value — check whether the "
                        "check it feeds then passes"))
    if not test:
        _unused_imports(rel, tree, lines, items)
        _commented_out_python(rel, lines, items)
        _todo_python(rel, text, items)
    return tree


def _unused_imports(rel, tree, lines, items):
    if rel.endswith("__init__.py"):
        return
    guarded = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Try) and any(_catches_import_error(h) for h in node.handlers):
            guarded.update(id(n) for n in ast.walk(node))
        if isinstance(node, ast.If) and (
                (isinstance(node.test, ast.Name) and node.test.id == "TYPE_CHECKING")
                or (isinstance(node.test, ast.Attribute) and node.test.attr == "TYPE_CHECKING")):
            guarded.update(id(n) for n in ast.walk(node))
    used = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            used.add(node.id)
        elif isinstance(node, ast.Attribute):
            root = node
            while isinstance(root, ast.Attribute):
                root = root.value
            if isinstance(root, ast.Name):
                used.add(root.id)
        elif isinstance(node, ast.Constant) and isinstance(node.value, str) and len(node.value) < 300:
            used.update(re.findall(r"[A-Za-z_]\w*", node.value))
    for node in tree.body:
        if id(node) in guarded or not isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            continue
        text = lines[node.lineno - 1]
        if "noqa" in text:
            continue
        for a in node.names:
            bound = a.asname or a.name.split(".")[0]
            if a.name != "*" and bound not in used:
                items.append(_item("unused_import", 2, rel, node.lineno, f"{bound}: {text}",
                                   f"`{bound}` is imported and never used"))


def _commented_out_python(rel, lines, items):
    block = []
    for i, line in enumerate(lines + [""], 1):
        s = line.strip()
        if s.startswith("#") and not s.startswith(("#!", "# -*-", "# type:", "# noqa", "# pragma")):
            body = s[1:]
            block.append((i, body[1:] if body.startswith(" ") else body))
            continue
        if len(block) >= 2:
            try:
                tree = ast.parse("\n".join(t for _, t in block))
            except (SyntaxError, ValueError):
                tree = None
            if tree is not None and any(isinstance(n, _RICH) for n in ast.walk(tree)):
                first = block[0][0]
                items.append(_item("commented_out_code", 2, rel, first, lines[first - 1],
                                   "code kept as a comment: dead, and it reads as live"))
        block = []


def _todo_python(rel, text, items):
    try:
        for tok in tokenize.generate_tokens(io.StringIO(text).readline):
            if tok.type == tokenize.COMMENT and _TODO.search(tok.string):
                items.append(_item("todo_comment", 2, rel, tok.start[0], tok.string,
                                   "a TODO/FIXME/HACK left in the code"))
    except (tokenize.TokenError, IndentationError, SyntaxError):
        return


def _function_bodies(rel, tree):
    out = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            span = (node.end_lineno or node.lineno) - node.lineno + 1
            if span >= DUPLICATE_MIN_LINES:
                dump = ast.dump(ast.Module(body=node.body, type_ignores=[]), annotate_fields=False)
                out.append((hashlib.sha1(dump.encode("utf-8")).hexdigest()[:16], rel, node.lineno, node.name))
    return out


def _duplicates(bodies):
    groups: dict = {}
    for h, rel, line, name in bodies:
        groups.setdefault(h, []).append((rel, line, name))
    out = []
    for h, sites in groups.items():
        if len(sites) < 2:
            continue
        rel, line, name = sites[0]
        where = ", ".join(f"{r}:{ln} {n}" for r, ln, n in sites[:4])
        out.append(_item("duplicate_function", 2, rel, line, "",
                         f"{len(sites)} identical function bodies — a fix to one misses the others: {where}",
                         redacted=f"def {name} — {len(sites)} identical copies", key=h))
    return out


def _unimported(files, imported, entry_text):
    out = []
    for rel in files:
        if "/" in rel or not rel.endswith(".py") or is_test_path(rel):
            continue
        stem = rel[:-3]
        if stem in ("setup", "conftest", "manage", "__init__", "noxfile", "tasks"):
            continue
        if stem not in imported and not re.search(r"\b" + re.escape(stem) + r"\b", entry_text):
            out.append(_item("module_never_imported", 3, rel, 1, rel,
                             "no module imports it and no documented command runs it — check whether it is dead"))
    return out


# ── JavaScript / TypeScript ───────────────────────────────────────────────
def _js_names(spec: str) -> list[str]:
    spec = spec.strip()
    m = re.match(r"\*\s+as\s+([\w$]+)$", spec)
    if m:
        return [m.group(1)]
    names = []
    head = spec.split("{", 1)[0].strip().rstrip(",").strip()
    if head:
        names.append(head)
    if "{" in spec:
        for part in spec.split("{", 1)[1].rsplit("}", 1)[0].split(","):
            part = re.sub(r"^\s*type\s+", "", part).strip()
            if part:
                names.append(part.split(" as ")[-1].strip())
    return [n for n in names if re.fullmatch(r"[A-Za-z_$][\w$]*", n)]


def _javascript(rel, text, lines, items):
    jsx = rel.endswith((".jsx", ".tsx"))
    run: list = []
    for i, line in enumerate(lines, 1):
        if _JS_EMPTY_CATCH.search(line):
            items.append(_item("broad_swallow", 2, rel, i, line, "an error handler that does nothing"))
        if _CONSOLE.search(line) and not _is_script_path(rel):
            items.append(_item("console_debug", 2, rel, i, line, "debug logging left in app code"))
        if _JS_COMMENT_TODO.search(line):
            items.append(_item("todo_comment", 2, rel, i, line, "a TODO/FIXME/HACK left in the code"))
        run = run + [i] if _JS_CODEY_COMMENT.match(line) else []
        if len(run) == 2:
            items.append(_item("commented_out_code", 2, rel, run[0], lines[run[0] - 1],
                               "code kept as a comment: dead, and it reads as live"))
    for m in _JS_IMPORT.finditer(text):
        rest = text[:m.start()] + text[m.end():]
        line_no = text.count("\n", 0, m.start()) + 1
        for name in _js_names(m.group("spec")):
            if jsx and name == "React":
                continue
            if not re.search(r"(?<![\w$.])" + re.escape(name) + r"(?![\w$])", rest):
                items.append(_item("unused_import", 2, rel, line_no,
                                   f"{name}: {m.group(0).splitlines()[0]}",
                                   f"`{name}` is imported and never used"))


# ── the scan ──────────────────────────────────────────────────────────────
def hygiene_census(repo, filing: str = "on") -> dict:
    """The hygiene block for facts.json: tier-1 and tier-2 items, tier-3 leads."""
    repo = Path(repo)
    files, capped = _tracked(repo)
    items, leads = _secret_files(repo, files)
    imported: set = set()
    bodies: list = []
    entry_text: list = []
    for rel in files:
        name = rel.rsplit("/", 1)[-1]
        suffix = Path(rel).suffix.lower()
        if suffix not in SCANNED_SUFFIXES and not name.startswith(".env"):
            continue
        text = _read(repo, rel)
        if text is None:
            continue
        lines = _lines(text)
        test = is_test_path(rel)
        if _ENTRY_FILE.search(rel):
            entry_text.append(text)
        leads += _env_placeholders(rel, name, lines)
        if not test:
            items += _secrets(rel, lines)
            items += _public_env(rel, lines)
            items += _open_rules(rel, name, suffix, lines)
            if suffix == ".sql":
                leads += [_item("rls_policy_using_true", 3, rel, i, line,
                                "a row-level-security policy that lets every row through — check it is meant to be public")
                          for i, line in enumerate(lines, 1) if _RLS_OPEN_POLICY.search(line)]
        if suffix not in CODE_SUFFIXES:
            continue
        if not test:
            items += _debuggers(rel, suffix, lines)
            leads += _line_leads(rel, lines)
            if len(lines) > OVERSIZED_LINES:
                items.append(_item("oversized_file", 2, rel, len(lines), "",
                                   f"{len(lines)} lines in one file — past what anyone, or any model, reads whole",
                                   redacted=f"{len(lines)} lines", key=""))
        if suffix == ".py":
            tree = _python(rel, text, lines, test, items, leads, imported)
            if tree is not None and not test:
                bodies += _function_bodies(rel, tree)
        elif not test:
            _javascript(rel, text, lines, items)
    items += _duplicates(bodies)
    leads += _unimported(files, imported, "\n".join(entry_text))
    _fingerprint(items)
    _fingerprint(leads)
    leads.sort(key=lambda it: (_LEAD_ORDER.get(it["kind"], 99), it["path"], it["line"]))
    counts: dict = {}
    for it in items:
        counts[it["kind"]] = counts.get(it["kind"], 0) + 1
    return {
        "status": "measured",
        "filing": "off" if filing == "off" else "on",
        "scope": {"files": len(files), "capped": capped, "file_cap": FILE_CAP},
        "counts_by_kind": dict(sorted(counts.items())),
        "items": items,
        "leads": leads[:LEAD_CAP],
        "leads_total": len(leads),
        "reading": ("tier 1 is filed by verdict-finalize as findings (source: hygiene); tier 2 is "
                    "the junk ledger, never a finding; leads are where to read first, never "
                    "findings by themselves"),
    }
